server:
  port: 8002

spring:
  main:
    allow-circular-references: true
  application:
    name: api-user-regist
  redis:
    port: 7001
    host: 47.113.202.125
    database: 0
    password: xiaopengroot123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://root:123@192.168.189.1:8761/eureka
feign:
  circuitbreaker:
    enabled: true
