server:
  port: 9001

spring:
  main:
    allow-circular-references: true
  application:
    name: user-check
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.113.202.125:3306/sgmall?Unicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      username: root
      password: admin123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      rate: 1
mybatis:
  type-aliases-package: com.sxp.entity
  mapper-locations: classpath:/mappers/*Mapper.xml


eureka:
  client:
    service-url:
      defaultZone: http://root:123@192.168.189.1:8761/eureka
